### ISSUE TITLE
Is JOSS support keystone v3?

### ISSUE THREAD

**Issue by RayOsLei** [javaswift/joss#112]

**Comment by effi-ofer** [comment]
Hi RayOsLei, JOSS does not support keystone v3, but you can still go through JOSS and provide an external authentication method.  You can see how it's done in this project https://github.com/SparkTC/stocator/blob/master/src/main/java/com/ibm/stocator/fs/swift/SwiftAPIClient.java.

**Comment by RayOsLei** [comment]
thanks ，I have solved it
