### ISSUE TITLE
How does JOSS determine what proxy servers to use?

### ISSUE THREAD

**Issue by porunov** [javaswift/joss#119]
Can we force JOSS to use special proxy servers (In local DC or certain proxy server)? Will it use only one or several proxy servers to contact?

**Comment by ferrys** [comment]
Hi @porunov, I'm not sure I understand exactly what you mean from this question. Could you perhaps expand what exactly you expect JOSS to do?

**Comment by ferrys** [comment]
Closing this in favor of #85
