### ISSUE TITLE
Can't get list of containers (/v1/{account})

### ISSUE THREAD

**Issue by Ezveus** [javaswift/joss#137]
Hi,

Trying to list containers ([/v1/{account}](https://developer.openstack.org/api-ref/object-storage/?expanded=show-account-details-and-list-containers-detail)), I got a `org.codehaus.jackson.map.exc.UnrecognizedPropertyException`.

Responsible field is `last_modified` which is not present in `org.javaswift.joss.command.shared.account.ContainerListElement`.

I propose to add the missing field or to ignore unknown fields.
I join both proposals as patches :

- [Add_lastModified_to_ContainerListElement.patch.txt](https://github.com/javaswift/joss/files/1285191/Add_lastModified_to_ContainerListElement.patch.txt)
- [Ignore_unknown_fields_in_ContainerListElement.patch.txt](https://github.com/javaswift/joss/files/1285190/Ignore_unknown_fields_in_ContainerListElement.patch.txt)

**Comment by ferrys** [comment]
Hi @Ezveus, as of v0.9.16, I am not having any problems listing all of the containers in an account. 

I am using something similar to this to produce the list: 
`Collection<Container> containers = account.list();`

Could you give some more information leading up to the exact problem you're encountering? Thanks!

**Comment by ferrys** [comment]
I'm going to close this, but feel free to reopen if you have any other issues.

**Comment by RayOsLei** [comment]
when swift version >2.10 such as 2.13 ,it occurs above problem@ferrys

**Comment by csommelet** [comment]
Field last_modified was added to containers list in swift 2.13.0. See https://github.com/openstack/swift/blob/master/CHANGELOG:

> Listing containers in accounts with json or xml now includes a
      `last_modified` time. This does not change any on-disk data, but simply
      exposes the value to offer consistency with the object listings on
      containers.

**Comment by ferrys** [comment]
@RayOsLei can you confirm PR #140 fixes the problem?

**Comment by RayOsLei** [comment]
@ferrys I tried to recompile the installation with this #140 fix，that's ok

**Comment by Ezveus** [comment]
@ferrys #140 works perfectly.
