### ISSUE TITLE
Segmentation for uploading objects via InputStream

### ISSUE THREAD

**Issue by nprncbl** [javaswift/joss#63]
While I understand why the current code cannot support segmentation for objects uploaded via an InputStream, I would suggest to refactor the whole UploadInstructions / UploadPayloadInputStream / ... code to support at least _indicating_ that the data that are streamed are going to be bigger than 5GiB (or whatever is configured as segment size on the OpenStack side), and to create the SegmentationPlan "on the fly" and not _before_ the actual upload of the object.

By doing this, storing objects via streaming will be possible even for objects larger than the configured max segment size.

**Comment by shrikantdesai** [comment]
any examples around use case ? I am using joss client trying to upload larger than 5GB file in chunks

**Comment by nrachan2004** [comment]
Is there an issue when we use uploadInstructions.deleteAfter. It does not seem to delete the segmented files
