### ISSUE TITLE
Hard coded PoolingClientConnectionManager settings

### ISSUE THREAD

**Issue by edwardsb** [javaswift/joss#78]
In: org.javaswift.joss.client.impl.ClientImpl

```
protected PoolingClientConnectionManager initConnectionManager() {
        PoolingClientConnectionManager connectionManager = new PoolingClientConnectionManager();
        connectionManager.setMaxTotal(50);
        connectionManager.setDefaultMaxPerRoute(25);
        return connectionManager;
    }
```

This seems a little limiting in certain applications. I ran into an issue where I have basically maxed out the 25 available connections and need more of them.

**Comment by roikku** [comment]
Why don't you implement your own *org.apache.http.client.HttpClient*? Then, when you create an account: *new AccountFactory(...).setHttpClient(myHttpClientImpl)*.

To implement your own HttpClient, you might find the following lines helpful:
```
PoolingClientConnectionManager connectionManager = new PoolingClientConnectionManager();
connectionManager.setMaxTotal(70);
connectionManager.setDefaultMaxPerRoute(50);
        
HttpClient httpClient = new DefaultHttpClient(connectionManager);
```
