### ISSUE TITLE
Help Me, getTempUrl Method Using Swift 401 Unauthorized: Temp URL invalid Please

### ISSUE THREAD

**Issue by action1020** [javaswift/joss#82]
Hi
I'm Hope Using JOSS, but getTempUrl is Problem, This is My Code
Please Help Me.
<pre>

AccountConfig config = new AccountConfig();
config.setUsername(userName);
config.setPassword(userPass);
config.setAuthUrl(authUrl);
config.setTempUrlHashPrefixSource(TempUrlHashPrefixSource.INTERNAL_URL_PATH);
config.setAuthenticationMethod(AuthenticationMethod.BASIC);

Account account = new AccountFactory(config).createAccount();
Container con = account.getContainer("g_g_EY6xqfJO_shared_test_n");
StoredObject obj = con.getObject("bfdce5c0-9e82-47ca-a63a-688f26b494fd558cf55369702d0d15120000");

String tempurl = obj.getTempGetUrl(600);
System.out.println("tempurl === " + tempurl );

</pre>

tempurl ===
https://localhost/v1/AUTH_bridge/g_g_EY6xqfJO_shared_test_n/bfdce5c0-9e82-47ca-a63a-688f26b494fd558cf55369702d0d15120000?temp_url_sig=698713f356ffa73b90abd6348909d2e46cf3cc33&temp_url_expires=1435307085

Then Browser Connecting Try TempUrl Http Error's 
401 Unauthorized: Temp URL invalid

I don't know this problem, please help me

thanks

**Comment by ctrl-alt-dev** [comment]
Did you use Account.setHashPassword like it says in the javadoc for getTempUrl?

**Comment by action1020** [comment]
hi ctrl-alt-dev !
setHashPassword is Required ?

**Comment by ctrl-alt-dev** [comment]
Yep :-) The temp_url_sig value is a digitally signed value. You can find the details in the [specs](http://docs.openstack.org/kilo/config-reference/content/object-storage-tempurl.html) 

    /**
    * Saves the password to the Account. The password will be used to create server side hashes. This is required for
    * TempURL (both GET and PUT). The server will match a generated hash against the hash that is passed in a
    * tempURL. If identical, it passed the first test. Note that if password is not set, TempURLs will not work.
    * Note that the password saved is the one set either in AccountConfig, or set with Account.setHashPassword(String).
    * @param hashPassword the password to use for generating the hashes
    */
